spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: zyzyqaz1
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zy.im.domain
  configuration:
    map-underscore-to-camel-case: true
